### ISSUE TITLE
Enable Minor Update 

### ISSUE THREAD

**Issue by IAMSKORPZ** [a4k-openproject/plugin.program.openwizard#105]
Hello how do enable Minor Updates in the wizard ?  Thanks

**Comment by drinfernoo** [comment]
It's a leftover, broken feature that was never fully implemented. There is no way currently.

**Comment by SerpentDrago** [comment]
@TeamSkorpz to be clear though you still need the minor= "http://"  placeholder in the build.txt file even though you can't actually use it

**Comment by IAMSKORPZ** [comment]
Yeah, I figured that out the hard way
