### ISSUE TITLE
Whitelist purpose ? Prevent addons or  addons zips deletion... 

### ISSUE THREAD

**Issue by siliconhippy** [a4k-openproject/plugin.program.openwizard#106]
Hi and great job !

What is the purpose of adding to the Whitelist?

1. If I don't add the specific add-on to the Whitelist, will it be deleted upon next boot?

Or is this Whitelist meant to delete non-included zip .Kodi/addons/ packages only upon next boot?

2. It would be nice to have All and None buttons: I counted 180+ addons and scripts etc in the Whitelist window !

Is there a way to select All or None from the xml files?

**Comment by JayDee696969** [comment]
Whitelist saves addons/data when you fresh install a build. Nothing gets deleted just by rebooting Kodi, its only to save specific stuff if you fresh install a build. Useful if you add addons that arent already part of a build and want to save from being deleted next time you update the build.

**Comment by siliconhippy** [comment]
Thanks 😊
I just wish there were a All or Nine button too.
Is there a way to add a All or None command by going into some xml file ?

**Comment by JayDee696969** [comment]
> Thanks 😊
> I just wish there were a All or Nine button too.
> Is there a way to add a All or None command by going into some xml file ?

That wouldnt make any sense, then you would just be backing up the whole build.  So just use the backup build option instead. Also would make any build updates useless if you are just backing up everything.

**Comment by siliconhippy** [comment]
Appreciate your answers !
It all makes sense now 😂
