### ISSUE TITLE
Startup Error 

### ISSUE THREAD

**Issue by sdstreams** [a4k-openproject/plugin.program.openwizard#108]
Hello, I tried searching online for some assistance but maybe someone on here knows. Whenever I install a test build using Openwizard it installs then when kodi reboots it looks like the build took but then an error pops up saying "Wizard did not install correctly! Installed: /Error count would I like to try again". There are 0 errors in log and my build is installed at this point but current build say none in wizard which affects any future build updates. Does anyone know how to fix this error. I have tried on a fresh clean kodi 17.6 and reinstalling the wizard but same error after every build I test install.

**Comment by drinfernoo** [comment]
Reopen with a log file attached if this is still an issue.
