### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hawksta** [a4k-openproject/plugin.program.openwizard#109]
Your build works perfectly on my old X96 Mini but on my new X96 Air it won't connect to half the wizards. I cannot run asked tests.  I cannot look at my ip and nax. I cannot modify cache and network presets. I'm trying to use your build to solve a problem with being unable to connect to premiumize.me links, but I also cannot connect to a new repository when I install it from zip file.  I can connect to all my old ones from a restored build (my own) but not from a new one even though I know everything is correct as i test it on my old x96 mini. Even if i go to update your addon from your repoisitory  it will fail.  Any help would be greatly appreciated. Thanks

**Comment by SerpentDrago** [comment]
OpenWizard is not a "build" its a tool that allows others to make builds and distribute them / maintain them . Others fork this "tool" and then use it to allow others to install their build . 

Your issues have nothing to do with OpenWizard itself

if you have issues with your build or kodi , i recommend you contact the people that maintain / distribute your build or other forums of kodi tech support . 

Thanks

**Comment by hawksta** [comment]
I understand that I'm just after any help or experience anyone has had previously.

**Comment by drinfernoo** [comment]
This doesn't sound like an issue with OpenWizard. Something else is going on.
