### ISSUE TITLE
Wizard Build Text File Error

### ISSUE THREAD

**Issue by bigo229** [a4k-openproject/plugin.program.openwizard#111]
Builds not showing in wizard  just error message

Getting error message.   Text file for builds not formatted correctly
I followed your guide at
 [Installing Builds](https://github.com/a4k-openproject/plugin.program.openwizard/wiki/Installing-Builds)

Also notifications giving error of Text file for notifications not formatted correctly

i have uploaded the text files to ifastnet.com & 000 webhost but getting same error but can view text files in browser ok

can you use a htm or html file instead of txt file

If anyone could help out with this i would be greatly appreciated for you help

Thanks

**Comment by SerpentDrago** [comment]
no , it must be a txt file formatted properly .  can't help you unless you post your builds.txt

**Comment by bigo229** [comment]
my build txt file

name="[COLORblue]****The Big One Kodi 18.x Leia Builds****[/COLOR]"
version="0.0"
url="http://"
gui="http://"
kodi="18"
theme="http://"
icon="http://"
fanart=""
preview="http://"
adult="no"
description="Our Kodi 18 Leia Lineup"

name="TBO SUPER "
version="1.0"
url="https://www.dropbox.com/s/ybm8uxbelwwxwis/TBO%2BSuperV1.0.zip?dl=1"
gui="http://"
kodi="18"
theme="http://"
icon="https://prehensible-items.000webhostapp.com/TBO/images/icon10.png"
fanart="https://prehensible-items.000webhostapp.com/TBO/images/fanartblack.jpg"
preview=""
adult="no"
description="Super Build. This is the super sized version of the build for Kodi 18 Leia" New Release

My notify txt file

1
|||


[COLOR white]WELCOME TO THE BIGONE Build WIZARD[/COLOR]
[COLOR white]Thank you for your continued support![/COLOR]
[COLOR white]Your Wizard has been updated to Ver. 1.1[/COLOR]
[COLOR white]This is our first builds![/COLOR]
[COLOR white][/COLOR]
[COLOR white][/COLOR]
[COLOR white][/COLOR]

I hope this helps
Thanks

**Comment by SerpentDrago** [comment]
Next time if you could actually upload the txt file or link it , formatting can get fucked up by just pasting it in and formatting matters . but i'll try . 

your missing a fanart placeholder  in your first entry
should be  
`fanart="http://"`

2nd entry 
Your missing preview placeholder , and you need to be sure description has " "  around it with no other " contained within   , it should read 

```
preview="http://"

description="Super Build. This is the super sized version of the build for Kodi 18 Leia" 
```

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/95989932-e631b580-0df8-11eb-989d-81143895d9ce.png)

**Comment by bigo229** [comment]
Hi, SerpentDrago

Here are the links;

http://thebigone.freesite.vip/TBO/texts/notify.txt

http://thebigone.freesite.vip/TBO/texts/buildsleia.txt

SerpentDrago

**Comment by SerpentDrago** [comment]
yeh ok , so read my previous comments and do the modifications you need to do . Looked at the direct links , seems to need the same changes i highlighted

**Comment by bigo229** [comment]
Thanks i will give that a try what about the notify.txt i get the same error with that file ?

**Comment by bigo229** [comment]
I changed the build txt file & tested on my 2 webhosts  ifastnet.com & 000 webhost but still the same error on one & not showing on the other.

I purchased premium paid hosting & the builds appeared & worked,

Not tested the notify txt file yet

bigo229
