### ISSUE TITLE
A Little Help Please

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/plugin.program.openwizard#112]
Drinfrnoo,  
So ive managed to update the Debrid, Trakt, and addon save data sections in the wizard with the addons of my choice and are working well now. (debridit.py, traktit.py, loginit.py)  I was hoping you could give me some guidance on one thing, visibility. Its coded now so the addons only are visible in these save data sections when the addons are actually installed. I would like to have them visible in the save data menu even if they arent installed. So when you click on something in the save data it prompts you to install the addon, instead of it not being visible at all. Do you think you can tell me where to look to change the visibility of these items for the save data sections? So you understand why, i have a build with addon shortcuts. All the addons arent installed untill you click on them, and naturally Kodi prompts you to install them. It cuts down build size this way. Ive made the wizard save data menus the first thing in the build. So instead of first browsing the build to install addons, and then going back to the save data menu, i would like them all visible in the save data menus before installing. Hope you understand. Appreciate it. Thank You!!

**Comment by oswaldchenby** [comment]
Drinfrnoo didn't develop Open Wizard but just hosting it nor he likely to provide any support. maybe a better idea ask that in a4k forum?

**Comment by JayDee696969** [comment]
> Drinfrnoo didn't develop Open Wizard but just hosting it nor he likely to provide any support. maybe a better idea ask that in a4k forum?

You know where this A4K forum might be?

**Comment by oswaldchenby** [comment]
> > Drinfrnoo didn't develop Open Wizard but just hosting it nor he likely to provide any support. maybe a better idea ask that in a4k forum?
> 
> You know where this A4K forum might be?

https://www.reddit.com/r/Addons4Kodi/

**Comment by drinfernoo** [comment]
> Drinfrnoo didn't develop Open Wizard but just hosting it nor he likely to provide any support. maybe a better idea ask that in a4k forum?

I... did create OpenWizard 🤔

@JayDee696969 If the builds don't have any add-ons installed in them to begin with, then there is no data to save 🤔

**Comment by JayDee696969** [comment]
> > Drinfrnoo didn't develop Open Wizard but just hosting it nor he likely to provide any support. maybe a better idea ask that in a4k forum?
> 
> I... did create OpenWizard 🤔
> 
> @JayDee696969 If the builds don't have any add-ons installed in them to begin with, then there is no data to save 🤔

Well, I have my own reasons. I do not preinstall many addons to save space. I prefer to have shortcuts to the addons so at first click it prompts you to install the selected addon. This slims down the bloat and allows users to only install the addons they prefer to use. I also set the debridit and traktit sections to open the Authorization window, so my goal is to use the debridit.py and traktit.py sections as "one stop shop" to install/authorize and save the data for these addons.  So by allowing them to be visible would help me accomplish this. Now you understand? So, im not asking you to ad this to the wizard, im just asking how to to this for my own reasons. Just asking for a little guidance cause i couldnt figure this part out. Thanks!

**Comment by drinfernoo** [comment]
My point is, if the user has never installed the add-on before, there is no data for them to save, so why have them go there? Once an add-on is installed, if "Save Data" is enabled, their data will be saved by default (whenever the wizard goes through a save cycle), once there is data to save.

**Comment by JayDee696969** [comment]
> My point is, if the user has never installed the add-on before, there is no data for them to save, so why have them go there? Once an add-on is installed, if "Save Data" is enabled, their data will be saved by default (whenever the wizard goes through a save cycle), once there is data to save.

Like i said above, Im not using it to only save the data, I also use it to open the debrid authorization, and Trakt authorizations for the addon. So if it was visible, on first click it would install the addon, and open the authorization, then save the data in one press.
`       'kaitord': {
        'name'     : '[B]***Kaito Anime Real Debrid***[/B]',
        'plugin'   : 'plugin.video.kaito',
        'saved'    : 'kaitord',
        'path'     : os.path.join(CONFIG.ADDONS, 'plugin.video.kaito'),
        'icon'     : os.path.join(CONFIG.ADDONS, 'plugin.video.kaito', 'icon.png'),
        'fanart'   : os.path.join(CONFIG.ADDONS, 'plugin.video.kaito', 'fanart.png'),
        'file'     : os.path.join(CONFIG.DEBRIDFOLD, 'kaito_rd'),
        'settings' : os.path.join(CONFIG.ADDON_DATA, 'plugin.video.kaito', 'settings.xml'),
        'default'  : 'rd.username',
        'data'     : ['rd.auth', 'rd.client_id', 'rd.expiry', 'rd.refresh', 'rd.secret', 'rd.username'],  
        'activate' : 'RunPlugin(plugin://plugin.video.kaito/authRealDebrid)'},`

**Comment by JayDee696969** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/45118866/110171761-2f939900-7dca-11eb-960d-b1a9fad54cae.png)

**Comment by drinfernoo** [comment]
You can remove lines 363 (for Trakt), 412 (for Debrid), and 460 (for Login) in `menu.py`, but be sure to de-indent the lines contained inside the corresponding `if` block, or else Python will error.

**Comment by JayDee696969** [comment]
> You can remove lines 363 (for Trakt), 412 (for Debrid), and 460 (for Login) in `menu.py`, but be sure to de-indent the lines contained inside the corresponding `if` block, or else Python will error.

Thank-You! Ill try that.
