### ISSUE TITLE
[Bug] Please Update for Matrix.

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/plugin.program.openwizard#113]
Matrix RC is now available: https://kodi.tv/article/kodi-19x-matrix-release-candidate.
It would be great to have a working wizard. Thanks!!

**Comment by drinfernoo** [comment]
As there is not currently a developer maintaining this project, it's unlikely that any updates will be made, unless someone steps forward and volunteers to update it.

**Comment by drinfernoo** [comment]
Got some help, and had been updated to 2.0.0 with initial Kodi 19 support.
