### ISSUE TITLE
[Bug] 1.4.7 broke the builds menu section

### ISSUE THREAD

**Issue by LoganWolverineX** [a4k-openproject/plugin.program.openwizard#116]
**Describe the[][Kodi log](https://www.dropbox.com/s/ov6a3oh4dmcqt76/kodi.log?raw=1) [Kodi log](https://www.dropbox.com/s/ov6a3oh4dmcqt76/kodi.log?raw=1) ()  bug**
I have a modified uservar.py file I have been using for a while which had no problems but now, it crashes openwizard when I go into the builds menu after After using my uservar.py file after openwizard has been updated to 1.4.7

**To Reproduce**
1. Update openwizard to 1.4.7
2. Replace uservar.py with my modified file
3. Open OpenWizard 
4. Go to (openwizard) builds
5. Openwizard crashes

**Expected behavior**
Does not crash openwizard when I go into (openwizard) builds after replacing the uservar.py with mines. 

**Platform**
Kodi 18.9

Log attached. 
https://www.dropbox.com/s/ov6a3oh4dmcqt76/kodi.log?raw=1

**Comment by drinfernoo** [comment]
Fixed in 1.4.7.1 🤦🏼‍♀️
