### ISSUE TITLE
[Bug] OpenWizard Won't Load Upon Updating to v2.0.4

### ISSUE THREAD

**Issue by LoganWolverineX** [a4k-openproject/plugin.program.openwizard#119]
**Describe the bug**
OpenWizard fails to open after updating to v2.0.4 on Kodi 19.

**To Reproduce**
1. Update OpenWizard to 2.0.4
2. Open OpenWizard
3. Error

**Log**
[kodi.log](https://github.com/a4k-openproject/plugin.program.openwizard/files/6185620/kodi.log)

**Platform**
Kodi 19

**Comment by SerpentDrago** [comment]
Works fine on my Kodi 19 on pc 

![image](https://user-images.githubusercontent.com/21133858/112083547-a1efd180-8b5d-11eb-8e52-0ab2a9233fb8.png)

**Comment by LoganWolverineX** [comment]
I found the issue. I usually have a modified user.py file so I can restore my build over the cloud on my devices. When updated, for some reason, I broke. I fixed my problem by overwriting the user.py file with the one I had modified. I’m good now. 

Not sure why it broke when I updated though. I would have thought the default user.py would have been installed when I updated.
