### ISSUE TITLE
[Add-on Request] Hide Menu Options

### ISSUE THREAD

**Issue by iTroNk** [a4k-openproject/plugin.program.openwizard#120]
Good sorry, I would like to remove options from the maintenance menu, log etc. Would it be possible to eliminate options?

Leave only the installation part.

**Comment by Arthur1967** [comment]
I'm just seeing this what is the repo for this and what can I apply it to I'm kind a new to github  thanks like which add-ons can I apply it to and what is it a repo￼￼￼￼

**Comment by drinfernoo** [comment]
@iTroNk, feel free to modify your own fork of the wizard any way you please. You can remove any section you like from the Python code, but it will no longer be supported if issues arise.

**Comment by iTroNk** [comment]
To hide it so that users do not appear when installing it, which file should I modify?

**Comment by drinfernoo** [comment]
Take a look at the files in the `gui` folder.
