### ISSUE TITLE
Errors produced from all addons after backup installed to Kodi Fork[Bug]

### ISSUE THREAD

**Issue by Zaxxon709** [a4k-openproject/plugin.program.openwizard#121]
**Describe the bug**
I've created a backup of my Kodi installation on my PC using Openwizard. It installs fine on a stock Kodi APK but not on my Kodi fork. Install goes fine without any errors noted from OpenWizard but once force closed and re-opened all add-ons produce the following error.

Error Contents: No module named packages.six.moves.http_client

**To Reproduce**
1. Backup build via OpenWizard on Windows PC 64bit
2. Re-install backup to a Kodi Fork with OpenWizard installed. Either 64bit or 32bit

**Expected behavior**
I expect to install the build with no errors and have binaries install as well.

**Screenshots**

**Platform**
Backup completed on a Windows 10 64bit PC
Backup installed on Android 7 tablet, Kodi Fork v18.9

**Additional context**
Kodi Fork has Openwizard added and all dependencies:
script.module.certifi
script.module.chardet
script.module.idna
script.module.requests
script.module.six
script.module.urllib3

Wizard runs fine on the fork and I am able to install other builds that have been backed up using another wizard. When I backup using Openwizard and restore to the fork is when the issue occurs.

Another important piece of information is the wizard will install my backup fine on any device running stock Kodi.

Hopefully, you are able to help. I like this wizard because it does the binaries (InputStream Adaptive, RTMP Input, PVR IPTV Simple Client etc...). With my extent of knowledge, I'm currently out of ideas. Thank you for any help in advance.

Kodi.log attached. I don't have a wizard.log but can get one if needed. However, there are no errors in the wizard log.

[kodi.log](https://github.com/a4k-openproject/plugin.program.openwizard/files/6242872/kodi.log)

**Comment by SerpentDrago** [comment]
Can you provide a link to kodi fork please? Your build?

Have you tried another kodi fork? Have you tried force updating that dependency that's failing? Disabling it restart then updating it?

**Comment by Zaxxon709** [comment]
> Can you provide a link to kodi fork please? Your build?
> 
> Have you tried another kodi fork? Have you tried force updating that dependency that's failing? Disabling it restart then updating it?

Thanks for the quote response! 

I'm out at the moment but will provide a link when I get back to my pc.

Yes, I've tried other forks with the sane result.

I've double check all versions of dependencies and they are the most current.

I have not disabled and retried an update of the dependency. I will give it a try.

The issue appears to be with urllib3 but I'm not 100% certian of that.

I've used open Wizard for quite some time with no issue until I decided to create a fork. That's when I noticed this issue. Maybe I have something messed up I'm not sure. Although, i have doubled checked everything I can think of.

**Comment by drinfernoo** [comment]
I'm not particularly experienced with other forks, as I don't support them...

But it could be a conflict between having the dependencies in your backup, and also already "installed" as part of your fork. I'm really not sure how Kodi handles it when you "install" an add-on that is already "built in".

**Comment by SerpentDrago** [comment]
^ thats a good point , you could simply try removing the dependencies in your zip . and trying that.

you have tried restarting kodi / device multiple times right ? seems like its trying to import from memory and its not finding it .

or your build you made on pc is including slightly platform specific deps or vis versa . 

https://www.reddit.com/r/Addons4Kodi/comments/mf0p0j/all_addons_produce_an_error_after_installing_kodi/

is that you ?

**Comment by SerpentDrago** [comment]
also your log is from a samsung android device (tv) not a pc , your saying this happens even when restoring a wizard backup from pc TO pc ?

**Comment by Zaxxon709** [comment]
> also your log is from a samsung android device (tv) not a pc , your saying this happens even when restoring a wizard backup from pc TO pc ?

No, only on the fork, PC is fine.

I have it sorted now. The dr's suggestion solved it. There must be a conflict when having the dependencies included in the build.zip and having them compiled within the fork.

Thanks for your help bud, I really appreciate it.

**Comment by Zaxxon709** [comment]
> ^ thats a good point , you could simply try removing the dependencies in your zip . and trying that.
> 
> you have tried restarting kodi / device multiple times right ? seems like its trying to import from memory and its not finding it .
> 
> or your build you made on pc is including slightly platform specific deps or vis versa .
> 
> https://www.reddit.com/r/Addons4Kodi/comments/mf0p0j/all_addons_produce_an_error_after_installing_kodi/
> 
> is that you ?

That's me! I got it sorted!

Thanks, guys @drinfernoo @SerpentDrago

**Comment by SerpentDrago** [comment]
@Zaxxon709  If you could update this and your reddit post with exactly how you solved it exact which addons youre removed from your zip . so we can just reference it or others find the fix in the future . 

I'm sure the wizard could add support for making a build "is this build for a fork that already has deps installed" and exclude them . but seeing as dr doens't have the time or desire to add features atm . its not going to happen lol . 

Thanks for the followup !

**Comment by Zaxxon709** [comment]
Solution: 
Remove the following OpenWizard dependencies from your build.zip. You'll find them in the 'addons' directory. Re-zip and install via OpenWizard that should be included in your fork.

Note that the above issue is only present if you've created a fork with OpenWizard included and have completed your backup using OpenWizard.

script.module.certifi
script.module.chardet
script.module.idna
script.module.requests
script.module.six
script.module.urllib3
