### ISSUE TITLE
[Bug] Error installing a theme

### ISSUE THREAD

**Issue by gtkingbuild** [a4k-openproject/plugin.program.openwizard#131]
After installing a theme, my skin Auramod is deactivated and the estuary skin is automatically put on

https://user-images.githubusercontent.com/68242121/117953054-0fc2a900-b316-11eb-91da-c8dffd736222.mp4

**Comment by drinfernoo** [comment]
This is not the behavior that I have. I've used the stock wizard with your builds file, and can install your build, along with a theme. After closing Kodi as prompted at the end of the install, your skin is applied when Kodi starts back up.

You have to reboot Kodi after you install a build or theme.
