### ISSUE TITLE
[Bug]function - Kodi 17 fix Error

### ISSUE THREAD

**Issue by ghost** [a4k-openproject/plugin.program.openwizard#132]
**Kodi v19.1**
Function of enabling all Addons in Wizard (v2.0.7)
Kodi 17 Fix not working (error).

**Steps to reproduce the behavior:**
1. Go to '...'Program Addon - > plugin.program.openwizard
2. Click on "Maintenance"
3. Click on "Misc Maintenance"
4. Scroll down to 'Kodi 17 Fix" Function 
5. See error in Wizard

**Platform**
Windows 10 and Android 8 and above.

**Comment by drinfernoo** [comment]
Please attach a log file.

**Comment by ghost** [comment]
[kodi.log](https://github.com/a4k-openproject/plugin.program.openwizard/files/6488139/kodi.log)

**Comment by drinfernoo** [comment]
The "Kodi 17 Fix" is not compatible with Matrix at this time. If you have a need to enable all add-ons, there is an option inside `Maintenance -> Addon Tools`.

**Comment by ghost** [comment]
OK Thanks.
