### ISSUE TITLE
[Add-on Request] Yoda, Realizer/Premiumizer

### ISSUE THREAD

**Issue by cartersball** [a4k-openproject/plugin.program.openwizard#17]
Add support for saving data from Yoda and Realizer/Premiumizer add-ons

**Comment by drinfernoo** [comment]
I've added Yoda with full functionality, but still need to add cache clearing for Premiumizer and Realizer, as well as figure out how to save `rdauth.json` in order to save RD for Realizer.

**Comment by icpryde** [comment]
also add Scrubs from the JewRepo

**Comment by drinfernoo** [comment]
@icpryde Open your own issue, ya freeloader! I'll get to it soon 👍

**Comment by icpryde** [comment]
@drinfernoo get scrubbing them scrubs you scrub 🥇

**Comment by kodiultimate** [comment]
@drinfernoo 

Ok, so Yoda has been added but for the hell of me I can't get it visible within my Kodi configuration. Of course addon is installed.

I though that there is something to do that the addon itself is named plugin.video.Yoda - starting yoda with capitol Y,  so I have changed it within wizard but still this addon is simply invisible lol

**Comment by drinfernoo** [comment]
@kodiultimate This isn't true anymore. Update Yoda.

**Comment by drinfernoo** [comment]
The only thing left to do here is add Realizer debrid saving, which will be a bit different from the rest. I'll open that as a separate issue.
