### ISSUE TITLE
[Add-on Request] Jor-El addon support

### ISSUE THREAD

**Issue by kodiultimate** [a4k-openproject/plugin.program.openwizard#18]
Hi,
Wondering if this could be added to wizard?

**What accounts does this add-on support?**
Trakt, Torrents (real debrid private API token), TMDb, IMDb, Oriondroid (API key)

**Where is this add-on available?**
Author : KoDIY repo : house of El

**Comment by drinfernoo** [comment]
Unless you have a current source for Jor-El, it appears to me as if it's been abandoned, and the repo taken down.

**Comment by kodiultimate** [comment]
Hi,
I'm sure it's still in this repo  http://kodihelp.net/repo/repository.houseofel.zip

**Comment by drinfernoo** [comment]
@kodiultimate Is there an **official**  source for this?

**Comment by kodiultimate** [comment]
Yes sir, that's official source.

**Comment by kodiultimate** [comment]
@drinfernoo any thoughts on this?

**Comment by drinfernoo** [comment]
I will look into it.
