### ISSUE TITLE
Save Login Info Dialogue results in error. 

### ISSUE THREAD

**Issue by bigpoppapaul** [a4k-openproject/plugin.program.openwizard#19]
When you go to Save Data>Keep Login Info, you get the following error. 

`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('mal-wonderfulsubs',)
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.program.aftermath\default.py", line 2616, in <module>
                                                elif mode=='login'          : loginMenu()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.program.aftermath\default.py", line 1239, in loginMenu
                                                if xbmc.getCondVisibility('System.HasAddon(%s)' % LOGINID[login]['plugin']):
                                            KeyError: ('mal-wonderfulsubs',)
                                            -->End of Python script error report<--`

This is on your absolute latest update, 0.4.8a after fixing the typo in loginit.

**Comment by kodiultimate** [comment]
I had same issue. Simply delete everything with word wonderfulsubs and it's working OK now

**Comment by drinfernoo** [comment]
Fixed, and with WonderfulSubs data saving working 👍
