### ISSUE TITLE
[addonUpdates] On Fresh Install Cancel and Re-initiate in DialogProgress, "default.addonupdate" is set to 2.

### ISSUE THREAD

**Issue by DaedalusBLN** [a4k-openproject/plugin.program.openwizard#23]
Greetings, whenever you have time, could you please check whether the bug I am experiencing also happens to you?

When a build installation/download (only tried Fresh Install) is cancelled from the DialogProgress window eg. by accident, and then restarted until completion addon auto-updates are set to off (2).

Does this happen to you as well? As my wizard was based on 0.2.4 Aftermath, to which I applied most of your updates, it may be just me.

I don't mean to bother, I am just wondering whether the issue exists for you as well. I think the issue lies somewhere within the definition of _addonUpdates_  in **wizard.py** (line 259 and onwards)  under **do=="set"** , where there is a line (268) configuring the setting _general.addonupdates_  to a "2" via JSONRPC. But I don't know what the wizard's purpose of setting it to 2 is, so I'm not just swapping it with a 0 and calling it fixed. 

Any assistance would be appreciated & 
thanks for the work you put into this.

**Comment by drinfernoo** [comment]
Are you talking about the global Kodi auto-updates setting? Because this shouldn't be touching that, as far as I'm aware.

**Comment by DaedalusBLN** [comment]
Precisely, I'm talking about the Kodi setting **general.addonupdates**  and the wizard setting **default.addonupdate**.

To Enable/Disable add-on auto-updates via JSONRPC. 0 is automatic, 1 is only notify, 2 is off.

(wizard.py, line 259 and onwards.)

**Comment by DaedalusBLN** [comment]
wizard.py lines 259 and onwards.

**Comment by drinfernoo** [comment]
Ah, ok. My recommendation would be... don't cancel a build download for the time being. I'll look at this eventually, but it's not a priority.

**Comment by DaedalusBLN** [comment]
Thank you. 🙏

**Comment by drinfernoo** [comment]
I'm going to close this as I've already marked #21 as part of the 0.7.0 milestone, which I'll be tackling somewhat soon. Thanks for opening this in the first place, but I'll likely be completely reworking *how* the wizard controls this setting in the future 👍
