### ISSUE TITLE
Issue with Build Text file

### ISSUE THREAD

**Issue by sp4rky82** [a4k-openproject/plugin.program.openwizard#24]
Hello, 
Great work by the way, it's greatly appreciated. I stumbled across this update, when i was looking why when Users was installing Kodi 18 Builds, they was getting File not a zip file. Hopefully, now we are adding this Wizard, this will resolve that.

We have set it all up, but when i click 'Builds Menu' it shows the Builds in the text file. Leia (2) Krypton(3)

But when i select a Build, it gives me: error reading the text file.
Build was not found in the Build list. What am i missing here?

In the wizard.py, it says that minor and info, is added in the build text. Is there any examples that I can look at as im using the older version of aftermath text file, which is giving me the error, and is the only thing holding us back from releasing this Wizard, which will hopefully sort he zip file error out

Many thanks

**Comment by drinfernoo** [comment]
https://www.github.com/drinfernoo/plugin.program.aftermath/wiki/ has examples of all of the usable text files.

Bear in mind that the files have to have *all* of the tags, and in *the same order*.
