### ISSUE TITLE
Issue with Kodi 18 on Mobile/Touchscreen devices

### ISSUE THREAD

**Issue by sp4rky82** [a4k-openproject/plugin.program.openwizard#25]
Hi Dr,

Sorry to bother you, I just wanted to ask about something which has had us baffled for days now. We have recently upgraded to this version of the Wizard, (Which  has been great) And just created a new 18 Apk, We are just having one issue, which we can't seem to sort out. Whenever anyone installs the Wizard and Build onto Kodi 18, Mobile phones the Build turns into a swipe screen, and the menus don't allow you to use them. Im presuming it is the same with tablet devices too, Have you heard anyone else ever having any similar issue? I'm not sure what we are doing wrong. 

Any advice, would be greatly appreciated. 
Many thanks.

**Comment by drinfernoo** [comment]
You're experiencing this on an unofficial Kodi 18-based fork?

**Comment by drinfernoo** [comment]
Closed for inactivity.

**Comment by sp4rky82** [comment]
Hi Drinferno,

I'm having this issue with official Kodi 18 Version and my own APK too.
Fine on Kodi 17.6 The issues ive mentioned are just with Kodi 18 for
some reason. My apologies for the late response.

**Comment by drinfernoo** [comment]
I'll see if I can replicate this, but I've never had the issue myself. Any specific devices having this behavior?

**Comment by SOOTTV** [comment]
It may be a skin issue, I have this issue with tian mod and Titan bingie

**Comment by drinfernoo** [comment]
@sp4rky82, what skin(s?) are you experiencing this with?

**Comment by sp4rky82** [comment]
Hi,

Its doing it on any Mobile Phone devices, and Tablets what i know about so
far. I think its more an isdue with Kodi 18. As its perfect on Kodi 17.6.

Cheers for the reply.

**Comment by SOOTTV** [comment]
I really don't think this is related to the wizard. If I manually move a build to a mobile device, the same thing happens. Running official Kodi 18 vs. a forked Kodi 18 yields the same results, I agree that it's probably a Kodi 18 issue. I also noticed that Samsung devices seem to be less affected than devices running a stock, or close to stock, android (Pixels, OnePlus, Huawei)
