### ISSUE TITLE
[Bug] Auto-Update dialog loses focus when widgets refresh on home screen

### ISSUE THREAD

**Issue by lasagnaforbrains** [a4k-openproject/plugin.program.openwizard#28]
**Describe the bug**
When an update to a build is pushed, the auto-update dialog (with the Fresh Install/Normal Install/Delay Update options) can lose focus when widgets on the home screen refresh which prevents you from selecting any options unless a mouse is used.

**To Reproduce**
1. Update a build
2. Launch Kodi with previous version still installed and widgets on the home screen that take longer to load than it takes for the wizard to notify there's an update.
3. Wait for the wizard to prompt for an update (either notification or auto-update dialog)
4. Wait for widgets on home screen to fully load
5. See the dialog lose focus and nothing can be selected unless a mouse is used.

**Expected behavior**
Options in the auto-update dialog can be selected.

**Platform**
Tested on Nvidia Shield and Windows 10 PC

**Additional context**
It's possible that skins with "Spotlight" widgets are causing it.

**Comment by drinfernoo** [comment]
What skin have you experienced this on? I haven't had this on either Aura or Arctic Zephyr 2, let alone Estuary (obviously, since it has no "widgets").

**Comment by drinfernoo** [comment]
Closing due to lack of a response from OP.
