### ISSUE TITLE
All Addon Auto Updates Disabled

### ISSUE THREAD

**Issue by sp4rky82** [a4k-openproject/plugin.program.openwizard#36]
Hi Dr Infernoo,

I have recently updated our Wizard, But whenever a Build is installed or Updated, all of the Auto Updates on the Addons are disabled. I'm not sure why this is happening. 

Regards

**Comment by drinfernoo** [comment]
Can you provide a copy of `wizard.log` from whenever a build is installed? That *is* a feature of the wizard, but not something that should be being triggered on a build install.

**Comment by drinfernoo** [comment]
Closing this due to lack of response from OP.
