### ISSUE TITLE
[Meta] Use Speed Tester from Kodi Repository

### ISSUE THREAD

**Issue by drinfernoo** [a4k-openproject/plugin.program.openwizard#38]

**Comment by JamesJB77** [comment]
Get busy Doc

**Comment by kodiultimate** [comment]
Hi @drinfernoo 

Any particular reason why would like to swap current speed test to offcial kodi repo one?
I'm happy with the current one :P

**Comment by drinfernoo** [comment]
@kodiultimate Simply to reduce code complexity. By using an external module, I wouldn't have to maintain or even *have* the speed tester code anymore. I haven't fully decided yet if I'm going to go this route, but it's a possibility.

**Comment by kodiultimate** [comment]
Fair point sir !
