### ISSUE TITLE
[Bug] Feature/Rewrite branch : 

### ISSUE THREAD

**Issue by SerpentDrago** [a4k-openproject/plugin.program.openwizard#39]
**Describe the bug**
Errors when saving trakt data or accessioning save data > keep trakt data"  menu after 

**To Reproduce**

go to save data > Keep trakt data , Save all . 

**Screenshots**
![image](https://user-images.githubusercontent.com/21133858/65567567-bcbf9680-df24-11e9-89d5-5c7ff15c30d6.png)

**Platform**
Kodi 18.4 / Latest Feature Rewrite branch version / PC

**Comment by drinfernoo** [comment]
Ah, jeez, that's silly. Just a typo, I'll get it tomorrow 😉
