### ISSUE TITLE
[Feature Request] Auto clean new frequency 

### ISSUE THREAD

**Issue by kodiultimate** [a4k-openproject/plugin.program.openwizard#44]
Hi @drinfernoo 

Would be able to add new auto clean frequency ? we have weekly as a maximum option at the moment, would be able to add once a month?
Thanks

**Comment by drinfernoo** [comment]
I am going to be adding monthly, just ran out of time today 👌

**Comment by kodiultimate** [comment]
Thank you sir! appreciate.
