### ISSUE TITLE
[Bug] Getting permission denied error while trying to remove addon data for uninstalled addons/backing up data

### ISSUE THREAD

**Issue by tstrul1** [a4k-openproject/plugin.program.openwizard#49]
**Describe the bug**
Hi,
Im Getting permission denied error while trying to remove addon data for uninstalled addons.
Im getting the same error even if im trying to open kodi as an administrator

Used to work great without any special permissions when im using this addon: https://forum.kodi.tv/showthread.php?tid=264018

**To Reproduce**
1. go to maintenance
2. Click on addons
3. click remove userdata
4. click remove userdata for deleted addons
5. error

**Expected behavior**
Remove unnecessary dirs.

**Platform**
Kodi 18.5
Windows 10 (64bit)

**Additional context**
Log file: http://paste.ubuntu.com/p/HZm7TD65Ds/

**Comment by tstrul1** [comment]
Well, I removed meta's old dir an it works flne. I guess I had troubles with permissions on this dir.
closing this issue

**Comment by tstrul1** [comment]
Actually encourted that again during build backup... I'm getting permissions denied on all sorts of files while other addons manage to handle them. re-opening this bug.

**Comment by drinfernoo** [comment]
Your original log has expired. I'll need a new one to try and replicate this issue, but from what I had seen before it expired, it seemed to me that you have Kodi installed in a directory with more advanced file permissions than your user profile has.

**Comment by tstrul1** [comment]
Latest log: http://paste.ubuntu.com/p/fR8BXW8qVG/

This is wired, Other addons manage to handle these files (or they just skip them without failing?). 

I didn't mess with windows default permissions on my userdata dir. In addition, I tried running kodi as an administrator and I still get permission denied.

**Comment by drinfernoo** [comment]
So the error is happening during the `special://` paths check, and it's trying to modify a file called `._addon.xml`, that's put there by Super Favorites. I'll have to look into a possible better way to do this or to exclude SF from that check.

**Comment by drinfernoo** [comment]
@tstrul1 have you tried this lately? I believe I may have fixed it with this commit: https://github.com/drinfernoo/plugin.program.openwizard/commit/55fbf3def8af2ac76ea541779094d72db9deedbf, which should be live in 1.2.9 on the repo.

**Comment by tstrul1** [comment]
Looks like ther is another error when i try to tackup: 
last error here: https://paste.ubuntu.com/p/3V7ydnyjV3/

**Comment by drinfernoo** [comment]
@tstrul1, could you try the latest commit on `develop`? Please turn on debug logging, and try to replicate the above condition. It appears that your latest log is hanging up on an invalid `addon.xml`, so I've added a debug log statement that should hopefully make it easier to track down.
