### ISSUE TITLE
[Bug] Fresh Install from Notification window on start up not working 

### ISSUE THREAD

**Issue by icpryde** [a4k-openproject/plugin.program.openwizard#53]
**Describe the bug**
When a build update is available you get the notification window on start up, it requests you click fresh install but literally nothing happens when you click it. Going into OpenWizard and clicking on builds then clicking the build you want to install via fresh install works as intended just not from the notification window.

**To Reproduce**

Have a build updated, restart kodi and then once you get the pop up notification saying a new build is available click on Fresh install.

**Platform**

I’ve tried this on NVIDIA shield and Windows 10 on 18.5.

**Comment by icpryde** [comment]
Log: https://paste.ubuntu.com/p/ksdcB9xTPQ/
Wizard log: https://paste.ubuntu.com/p/Y6xcSjrd8X/

**Comment by tomtomclub** [comment]
in the config uservar.py  see notification  yes out in No

**Comment by drinfernoo** [comment]
Is this working now @icpryde ?

**Comment by tomtomclub** [comment]
Yes thanks

Op vr 24 jan. 2020 17:38 schreef drinfernoo <notifications@github.com>:

**Comment by icpryde** [comment]
Yes it’s working
