### ISSUE TITLE
[Feature Request] remove Normal Install from Builds

### ISSUE THREAD

**Issue by icpryde** [a4k-openproject/plugin.program.openwizard#54]
Relatively simple feature request, we’ve discussed this before but thought I’d put it here as a reminder.

Simply remove “normal install” from the notification window and from the builds section.

This makes it easier for people to not click the wrong one but also it doesn’t serve much of a purpose and 99% of the time you should use Fresh Install.

**Comment by drinfernoo** [comment]
So would you propose that every install be a forced fresh install?

**Comment by icpryde** [comment]
> So would you propose that every install be a forced fresh install?

That’s honestly what I do for every install no matter how big or small as normal install has the potential to mess things up where fresh install never will.
