### ISSUE TITLE
[Bug] Build update via update prompt not working. No error.

### ISSUE THREAD

**Issue by aexarch** [a4k-openproject/plugin.program.openwizard#59]
**Describe the bug**
Updating via the build update prompt not working, at least not for Fresh Install, didn't try Normal. Using v1.2.7 as base, going to update today and see if the problem persists.

**To Reproduce**
1. Update version number of build in builds.txt (ZIP direct link works fine when updating via the build menu within OpenWizard, I have not changed any of your code.)
2. Restart Kodi
3. Wait for update prompt.
4. Select Fresh Install.

**Expected behavior**
Feature should behave as in build menu and initiate an update with the yesno dialogue.

**Screenshots**

**Platform**
Windows 10 x64, Android x64
Kodi 18.5

Tried editing build_update_prompt.xml to remove the install buttons and create a new button with an onclick action via ActivateWindow, RunAddon or RunPlugin to open the wizard's build menu. That also failed. Double-checked my syntax. I don't know why this happens, if you need more info let me know. Which file should I look at for this prompt? Tools.py?

**Comment by drinfernoo** [comment]
Try again with latest master branch. 1.2.8 was merged three days ago to fix this.
