### ISSUE TITLE
[Bug] Wizard restores data on boot , causing major issues 

### ISSUE THREAD

**Issue by SerpentDrago** [a4k-openproject/plugin.program.openwizard#62]
The wizard by default shouldn't restore data on EVERY boot , it should only restore data after build install/restore.

The reason for this being a major problem , is the average user is not going to know that they can't simply change say .. priority in Resolver , and know to then go into wizard and save that new data . if they dont' when they restart kodi their old priority will be restored . Very confusing and not good.

**Comment by Demonseeed** [comment]
Is this why OpenWizard thinks it is a first time run every time I reboot Kodi?
![A3CE6D43-DDEC-4A6B-8501-AF0F950E4853](https://user-images.githubusercontent.com/29167580/71770512-8eb9fd00-2eea-11ea-882d-8c6263387ee2.jpeg)

**Comment by drinfernoo** [comment]
@Demonseeed That should've been fixed many versions ago. Are you up-to-date?

**Comment by Demonseeed** [comment]
Yes, I am using version 1.2.8. This sounded initially like it might be related, but maybe not. Want me to create a separate issue?

**Comment by drinfernoo** [comment]
@Demonseeed Sure, with a debug log if you don't mind 👍
