### ISSUE TITLE
[Addon Support] FEN

### ISSUE THREAD

**Issue by Tinuz97** [a4k-openproject/plugin.program.openwizard#64]
FEN Cleaning in the cleaning options.
Just a reminder lol (asked in the Telegram group a while ago, you answered to set a reminder if forgotten) :) 

Thx.

**Comment by drinfernoo** [comment]
Will do! I need to add it for it's other integrations too 😉

**Comment by Tinuz97** [comment]
Any love for Fen @drinfernoo 🙏
