### ISSUE TITLE
Selecting Addons for Backup [Feature Request]

### ISSUE THREAD

**Issue by theKosmikOne** [a4k-openproject/plugin.program.openwizard#65]
Please, allow a 'select all' for Addons Backup. Selecting every one of my 297 addons makes my little keyboard cry.

Thank You for stepping up and filling a void where backups were not readily available. I like the work you are doing !

**Comment by SerpentDrago** [comment]
are you talking about the Maintenance > backup > addon pack  menu ? 

Is there any reason you are needing to backup all addons into a single pack  ? are you not better off just backing up the entire build if doing that ?

**Comment by theKosmikOne** [comment]
Wow, very fast response !

 

Yes, it has always been best to restore from a full backup, for myself and for when I share my builds with my friends. Quick and easy for all. Was a long time user of USB-DVD Wizard.

 

Reason for backup of all addons – For a newer or different skin for myself or others. I use 2 Nvidia Shields but some boxes are less capable and Firesticks are a joke. So I occasionally have to use some very bare-ass light skins. I use skins because the stock skin of any Kodi is an unintuitive eyesore.

 

I’ll bet may others follow the same practice.

 

Thank you very much. I wish you luck with your endevours.

**Comment by SerpentDrago** [comment]
Fair enough , Dr is the dev he will have to figure out if he can do this or not . 

You know you could have a gui fix backup , this backs up kodi settings / skin settings / skin shortcuts . 

it could work well for you .  you make a "base build" , then have different gui fixs for each skin (adjust skin and settings , then make a gui fix backup  .. just  a thought

**Comment by theKosmikOne** [comment]
Cool idea. Base builds are a good idea and I have always done that with Windows (different strokes for different folks). I simply had not thought of following the same concept in Kodi. LOL, I have trigger fingered to get away from the stock GUI too fast !

 

So –

 

Base build

 

Addons with configurations

 

Skin(s) with shortcuts +skin adjustments

 

More work ! I have found that the better you get at something, you can end up putting a lot more work into what you do.

 

I simply though GUI fix backup would only apply to the skin I was using. An error in thinking by applying it at the custom skin stage. I will put your suggestion to use on next build. Thank you.

 

I would like to still make use of a complete addons backup. It’s a belt and suspenders mentality, aka - OCD.

**Comment by drinfernoo** [comment]
I don't understand... You want to backup all add-ons during a build backup? That is already what happens.

**Comment by theKosmikOne** [comment]
True. But I also want to install my addons to other skins. Reason, lower spec boxes require very light skins. Other people do this also.

**Comment by drinfernoo** [comment]
I would recommend either making multiple builds, or one large build (though I can't say I recommend builds with ~300 add-ons), which leverages themes to include different skins.

In any case, Kodi's "multiselect" dialog doesn't allow for a "Select All" or "Select None"... so it's unlikely I could implement it without a custom dialog, which I'm not too keen on.
