### ISSUE TITLE
[Bug] Making local build backup on shield 

### ISSUE THREAD

**Issue by SerpentDrago** [a4k-openproject/plugin.program.openwizard#68]
Local build backup on shield is not creating the .txt info file

**Comment by drinfernoo** [comment]
Can you get me a log file of this?

**Comment by drinfernoo** [comment]
I'm unable to reproduce this. I simply went to `Maintenance -> Back up/Restore -> [Back Up]: Build` (on my Shield), and completed a backup. After doing so, all of the expected files were created: the build zip, a guifix zip, and the info text file.
