### ISSUE TITLE
[Bug] Error received importing backup

### ISSUE THREAD

**Issue by AKBraves** [a4k-openproject/plugin.program.openwizard#69]
Receiving an error trying to import a markup generated from both PC and shield to shield (same as backup). Log below

http://paste.ubuntu.com/p/5pFf4rvYCv/

**Comment by SerpentDrago** [comment]
you say import , you mean saved data like trakt / debrid / logins ? 

or are you talking about Restoring a backed up build ?

**Comment by drinfernoo** [comment]
@AKBraves can you test the latest version on `develop` for me? I think I may have found the cause of this.
