### ISSUE TITLE
Not able to install apk's from apk installer in latest aftermath wizard on Kodi 18 32bit

### ISSUE THREAD

**Issue by bringyoutolife** [a4k-openproject/plugin.program.openwizard#7]
This issue I am about to describe is in the official release of Kodi 18 32 bit with the latest  version of aftermath wizard installed. I tested on Firestick 4k, fire TV cube, and a moto g6 phone.

 An issue exists with not being able to install apks from the Apk Installer section. You are able to download them and the spmc install pop up image shows up but when you click ok it doesnt launch the installation screen, instead it takes you back to the dialog asking if you want to download that apk so you can't install any apk files through the wizard anymore. Please fix this issue 🙏

**Comment by simonchunk** [comment]
Does this workaround help our cause?

https://forum.kodi.tv/showthread.php?tid=339210

**Comment by drinfernoo** [comment]
@simonchunk Unfortunately, I've been unable to get the code from that thread to work. There's an [open pull request](https://github.com/xbmc/xbmc/pull/15577) that purports to solve this, but I can't get it working either. Feel free to encourage the Kodi team to merge that PR, but until then, I'm closing this issue as wontfix.

**Comment by drinfernoo** [comment]
Considering this: xbmc/repo-scripts#1236

I think this may be a possibility in the near future.
