### ISSUE TITLE
macOS Catalina error log - Unable to open Wizard

### ISSUE THREAD

**Issue by kbxy88** [a4k-openproject/plugin.program.openwizard#70]
Getting the following error when trying to use Open Wizard when using macOS Catalina.  

- Tried a fresh install of Kodi and just installing the wizard and I can't access any part of wizard.

- I've made a full zip of a build where Open Wizard is fully functional on another computer(macOS Mojave (Catalina's predecessor)).

After adding those zipped files to Catalina same errors occur.

![IMG_2652](https://user-images.githubusercontent.com/47716487/72941733-beb52d00-3d3f-11ea-8011-6b56f462a83c.JPG)

**Comment by drinfernoo** [comment]
>After adding those zipped files to Catalina same errors occur.

What do you mean by this?

**Comment by kbxy88** [comment]
> > After adding those zipped files to Catalina same errors occur.
> 
> What do you mean by this?

I zipped the build from Open wizard on the OS X Mojave’s that wizard is working fine. Since I can’t open the wizard on OSX Catalina I unzipped the files and put those folders from build in my .kodi folder. The userdata & add on data 

My long story short was basically I did a fresh install with just the wizard first and also tried bringing a zipped build and neither worked

**Comment by drinfernoo** [comment]
Do you have a file called `/Users/nukka./Library/Logs/ims.log`? And is that the folder Kodi dumps logs into on OS X? 

EDIT: It does appear that is the path where OS X dumps log files for pretty much *everything* 😳

**Comment by kbxy88** [comment]
> Do you have a file called `/Users/nukka./Library/Logs/ims.log`? And is that the folder Kodi dumps logs into on OS X?
> 
> EDIT: It does appear that is the path where OS X dumps log files for pretty much _everything_ 😳

<img width="366" alt="Screen Shot 2020-01-24 at 4 03 04 PM" src="https://user-images.githubusercontent.com/47716487/73103881-16c86c80-3ec3-11ea-8d70-d628e3f57435.png">
This is what I see

**Comment by drinfernoo** [comment]
Can you try the latest version from `develop`? I think I've probably fixed it.

**Comment by SerpentDrago** [comment]
@kbxy88  can you test this latest DEVELOP  branch ?

**Comment by kbxy88** [comment]
> @kbxy88 can you test this latest DEVELOP branch ?

Hey sorry I had tested then and I haven’t had any issues since he released the Develop Branch. Sorry was chatting with Doc on Discord. I think safe to close now.

**Comment by SerpentDrago** [comment]
fixed in 
55fbf3def8af2ac76ea541779094d72db9deedbf
