### ISSUE TITLE
[Feature Request] Option to save/retain guisettings.xml

### ISSUE THREAD

**Issue by SOOTTV** [a4k-openproject/plugin.program.openwizard#71]
Option to save/retain guisettings.xml on build install

That's about it lol

Thx!

**Comment by drinfernoo** [comment]
I will knock this one out for 1.3.0 probably.

**Comment by drinfernoo** [comment]
Can you test latest `develop` branch, and see if this is working for you now?

**Comment by SerpentDrago** [comment]
@SoulTV Can you test this feature on latest Dev branch ?
