### ISSUE TITLE
[Bug] Keep login info 

### ISSUE THREAD

**Issue by xyzfre** [a4k-openproject/plugin.program.openwizard#75]
I used to get a pop up for when keep login info ,notice the past week it doesn’t show up anymore even if I manually click keep login  info nothing happens

**Comment by drinfernoo** [comment]
I would need to know which version of the wizard you're running, and probably see a log file.

**Comment by xyzfre** [comment]
I am on the lates version 1.3.0 and right after the update got a log error something about 701 error everything seems to work except keep login info I will post the log tomorrow unfortunately already turned off my TV and in bed appreciate your response will keep you posted thank you for all your hard work

**Comment by xyzfre** [comment]
1.3.1 fix the error Thank you for all your hard work and for creating an amazing wizard
