### ISSUE TITLE
[Bug] Error on restoring local build

### ISSUE THREAD

**Issue by dashzombie** [a4k-openproject/plugin.program.openwizard#77]
**Describe the bug**
I create and backup a build on my Windows 10 machine and copy the build files over to my Firestick. Then I restore local build on my Firestick only lately I have been getting an error when trying to restore a local build. 

It gives me the same error when I tried to restore on the original Windows 10 machine too even on older builds that I know worked before.

**To Reproduce**
1. Go to 'Maintenance'
2. Click on 'Backup/Restore'
3. Scroll down to '[Restore] Local Build'
4. I choose the build I copied over.
5. Error

**Platform**
Windows 10, Firestick 4K, Kodi 18.5

**Additional context**
Log: http://paste.ubuntu.com/p/HdCvtSTkRz/

**Comment by drinfernoo** [comment]
Can you please test latest develop branch for me? I've fixed the error I believe, but need confirmation.

**Comment by dashzombie** [comment]
That worked. Thank you! You saved me rebuilding this thing from scratch.
