### ISSUE TITLE
[Bug]Kodi 17.6 fresh install of OpenWizard v 1.3.4 Killing Start Up Script

### ISSUE THREAD

**Issue by Shark5588** [a4k-openproject/plugin.program.openwizard#81]
Kodi 17.6 fresh install of OpenWizard Killing Start Up Script

----Wizard.log
[2020-04-02 10:20:41] Killing Start Up Script

/////////////////////////// Kodi Log //////////////////////

10:20:40.017 T:3816  NOTICE: special://profile/ is mapped to: special://masterprofile/
10:20:40.017 T:3816  NOTICE: -----------------------------------------------------------------------
10:20:40.018 T:3816  NOTICE: Starting Kodi (17.6 Git:20171114-a9a7a20). Platform: Windows NT x86 32-bit
10:20:40.018 T:3816  NOTICE: Using Release Kodi x32 build
10:20:40.018 T:3816  NOTICE: Kodi compiled Nov 14 2017 by MSVC 190024215 for Windows NT x86 32-bit version 10.0 (0x0A000000)
10:20:40.018 T:3816  NOTICE: Running on Dell Inc. Latitude E5420 with Windows 7 SP1, kernel: Windows NT x86 64-bit version 6.1
10:20:40.020 T:3816  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
10:20:40.020 T:3816  NOTICE: Host CPU: Unknown, 4 cores available
10:20:40.021 T:3816  NOTICE: Desktop Resolution: 1366x768 32Bit at 40Hz
10:20:40.021 T:3816  NOTICE: Running with restricted rights
10:20:40.021 T:3816  NOTICE: Aero is enabled
10:20:40.021 T:3816  NOTICE: special://xbmc/ is mapped to: C:\Program Files (x86)\Kodi
10:20:40.021 T:3816  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files (x86)\Kodi
10:20:40.021 T:3816  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files (x86)\Kodi/addons
10:20:40.021 T:3816  NOTICE: special://masterprofile/ is mapped to: C:\Users\User\AppData\Roaming\Kodi\userdata
10:20:40.021 T:3816  NOTICE: special://home/ is mapped to: C:\Users\User\AppData\Roaming\Kodi\
10:20:40.021 T:3816  NOTICE: special://temp/ is mapped to: C:\Users\User\AppData\Roaming\Kodi\cache
10:20:40.021 T:3816  NOTICE: special://logpath/ is mapped to: C:\Users\User\AppData\Roaming\Kodi\
10:20:40.021 T:3816  NOTICE: The executable running is: C:\Program Files (x86)\Kodi\kodi.exe
10:20:40.033 T:3816  NOTICE: Local hostname: Shark55-PC
10:20:40.033 T:3816  NOTICE: Log File is located: C:\Users\User\AppData\Roaming\Kodi\/kodi.log
10:20:40.033 T:3816  NOTICE: -----------------------------------------------------------------------
10:20:40.048 T:3816  NOTICE: load settings...
10:20:40.069 T:3816 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
10:20:40.070 T:3816 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
10:20:40.077 T:3816  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
10:20:40.077 T:3816  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
10:20:40.077 T:3816  NOTICE: Default Video Player: VideoPlayer
10:20:40.077 T:3816  NOTICE: Default Audio Player: paplayer
10:20:40.077 T:3816  NOTICE: Disabled debug logging due to GUI setting. Level 0.
10:20:40.077 T:3816  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
10:20:40.077 T:3816  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
10:20:40.078 T:3816  NOTICE: Loaded playercorefactory configuration
10:20:40.078 T:3816  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
10:20:40.078 T:3816  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
10:20:40.099 T:3816  NOTICE: Running database version Addons27
10:20:40.297 T:3816  NOTICE: ADDONS: Using repository repository.xbmc.org
10:20:40.377 T:7776  NOTICE: Found 2 Lists of Devices
10:20:40.377 T:7776  NOTICE: Enumerated DIRECTSOUND devices:
10:20:40.377 T:7776  NOTICE:     Device 1
10:20:40.377 T:7776  NOTICE:         m_deviceName      : {A8D5299C-211D-450D-8375-1F2984058676}
10:20:40.377 T:7776  NOTICE:         m_displayName     : Headphones - Communications Headphones (IDT High Definition Audio CODEC)
10:20:40.377 T:7776  NOTICE:         m_displayNameExtra: DIRECTSOUND: Communications Headphones (IDT High Definition Audio CODEC)
10:20:40.377 T:7776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:20:40.377 T:7776  NOTICE:         m_channels        : FL,FR
10:20:40.377 T:7776  NOTICE:         m_sampleRates     : 48000
10:20:40.377 T:7776  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
10:20:40.377 T:7776  NOTICE:         m_streamTypes     : No passthrough capabilities
10:20:40.377 T:7776  NOTICE:     Device 2
10:20:40.377 T:7776  NOTICE:         m_deviceName      : {B054B185-3AA1-47CC-A23B-7DA5797A309E}
10:20:40.377 T:7776  NOTICE:         m_displayName     : Speakers - Speakers / Headphones (IDT High Definition Audio CODEC)
10:20:40.377 T:7776  NOTICE:         m_displayNameExtra: DIRECTSOUND: Speakers / Headphones (IDT High Definition Audio CODEC)
10:20:40.377 T:7776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:20:40.377 T:7776  NOTICE:         m_channels        : FL,FR
10:20:40.377 T:7776  NOTICE:         m_sampleRates     : 48000
10:20:40.377 T:7776  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
10:20:40.377 T:7776  NOTICE:         m_streamTypes     : No passthrough capabilities
10:20:40.377 T:7776  NOTICE:     Device 3
10:20:40.377 T:7776  NOTICE:         m_deviceName      : default
10:20:40.377 T:7776  NOTICE:         m_displayName     : default
10:20:40.377 T:7776  NOTICE:         m_displayNameExtra:
10:20:40.377 T:7776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:20:40.377 T:7776  NOTICE:         m_channels        : FL,FR
10:20:40.377 T:7776  NOTICE:         m_sampleRates     : 48000
10:20:40.377 T:7776  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
10:20:40.377 T:7776  NOTICE:         m_streamTypes     : No passthrough capabilities
10:20:40.378 T:7776  NOTICE: Enumerated WASAPI devices:
10:20:40.378 T:7776  NOTICE:     Device 1
10:20:40.378 T:7776  NOTICE:         m_deviceName      : {A8D5299C-211D-450D-8375-1F2984058676}
10:20:40.378 T:7776  NOTICE:         m_displayName     : Headphones - Communications Headphones (IDT High Definition Audio CODEC)
10:20:40.378 T:7776  NOTICE:         m_displayNameExtra: WASAPI: Communications Headphones (IDT High Definition Audio CODEC)
10:20:40.378 T:7776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:20:40.378 T:7776  NOTICE:         m_channels        : FL,FR
10:20:40.378 T:7776  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100
10:20:40.378 T:7776  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
10:20:40.378 T:7776  NOTICE:         m_streamTypes     : No passthrough capabilities
10:20:40.378 T:7776  NOTICE:     Device 2
10:20:40.378 T:7776  NOTICE:         m_deviceName      : {B054B185-3AA1-47CC-A23B-7DA5797A309E}
10:20:40.378 T:7776  NOTICE:         m_displayName     : Speakers - Speakers / Headphones (IDT High Definition Audio CODEC)
10:20:40.378 T:7776  NOTICE:         m_displayNameExtra: WASAPI: Speakers / Headphones (IDT High Definition Audio CODEC)
10:20:40.378 T:7776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:20:40.378 T:7776  NOTICE:         m_channels        : FL,FR
10:20:40.378 T:7776  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100
10:20:40.378 T:7776  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
10:20:40.378 T:7776  NOTICE:         m_streamTypes     : No passthrough capabilities
10:20:40.378 T:7776  NOTICE:     Device 3
10:20:40.378 T:7776  NOTICE:         m_deviceName      : default
10:20:40.378 T:7776  NOTICE:         m_displayName     : default
10:20:40.378 T:7776  NOTICE:         m_displayNameExtra:
10:20:40.378 T:7776  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:20:40.378 T:7776  NOTICE:         m_channels        : FL,FR
10:20:40.378 T:7776  NOTICE:         m_sampleRates     : 192000,96000,88200,48000,44100
10:20:40.378 T:7776  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
10:20:40.378 T:7776  NOTICE:         m_streamTypes     : No passthrough capabilities
10:20:40.442 T:3816  NOTICE: Found screen: Generic PnP Monitor on Intel(R) HD Graphics 3000, adapter 0.
10:20:40.442 T:3816  NOTICE: Primary mode: 1366x768@ 40.00 - Full Screen
10:20:40.450 T:3816  NOTICE: Additional mode: 320x200@ 40.00 - Full Screen
10:20:40.450 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.450 T:3816  NOTICE: Additional mode: 320x200@ 60.00 - Full Screen
10:20:40.452 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.452 T:3816  NOTICE: Additional mode: 320x240@ 40.00 - Full Screen
10:20:40.452 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.452 T:3816  NOTICE: Additional mode: 320x240@ 60.00 - Full Screen
10:20:40.454 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.454 T:3816  NOTICE: Additional mode: 400x300@ 40.00 - Full Screen
10:20:40.454 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.454 T:3816  NOTICE: Additional mode: 400x300@ 60.00 - Full Screen
10:20:40.456 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.456 T:3816  NOTICE: Additional mode: 512x384@ 40.00 - Full Screen
10:20:40.457 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.457 T:3816  NOTICE: Additional mode: 512x384@ 60.00 - Full Screen
10:20:40.459 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.459 T:3816  NOTICE: Additional mode: 640x400@ 40.00 - Full Screen
10:20:40.459 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.459 T:3816  NOTICE: Additional mode: 640x400@ 60.00 - Full Screen
10:20:40.461 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.461 T:3816  NOTICE: Additional mode: 640x480@ 40.00 - Full Screen
10:20:40.461 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.461 T:3816  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
10:20:40.463 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.463 T:3816  NOTICE: Additional mode: 800x600@ 40.00 - Full Screen
10:20:40.463 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.463 T:3816  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
10:20:40.465 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.465 T:3816  NOTICE: Additional mode: 1024x768@ 40.00 - Full Screen
10:20:40.465 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.465 T:3816  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
10:20:40.467 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.467 T:3816  NOTICE: Additional mode: 1280x720@ 40.00 - Full Screen
10:20:40.468 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.468 T:3816  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
10:20:40.469 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.469 T:3816  NOTICE: Additional mode: 1360x768@ 40.00 - Full Screen
10:20:40.470 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.470 T:3816  NOTICE: Additional mode: 1360x768@ 60.00 - Full Screen
10:20:40.470 T:3816  NOTICE: Previous line repeats 2 times.
10:20:40.470 T:3816  NOTICE: Additional mode: 1366x768@ 40.00 - Full Screen
10:20:40.471 T:3816  NOTICE: Additional mode: 1366x768@ 60.00 - Full Screen
10:20:40.471 T:3816  NOTICE: Checking resolution 15
10:20:40.712 T:6732  NOTICE: Running database version Addons27
10:20:40.714 T:6732  NOTICE: Running database version ViewModes6
10:20:40.968 T:6732  NOTICE: Running database version MyMusic60
10:20:40.980 T:6732  NOTICE: Running database version MyVideos107
10:20:40.984 T:6732  NOTICE: Running database version TV29
10:20:40.988 T:6732  NOTICE: Running database version Epg11
10:20:41.135 T:3816 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
10:20:41.233 T:3816  NOTICE: initialize done
10:20:41.233 T:3816  NOTICE: Running the application...
10:20:41.233 T:3816  NOTICE: starting upnp client
10:20:41.238 T:2748  NOTICE: ES: Starting UDP Event server on port 9777
10:20:41.238 T:2748  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
10:20:41.741 T:5780  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: Killing Start Up Script

**Comment by SerpentDrago** [comment]
I'm sorry. what exactly do you think is wrong? also if you could please next time link to log instead of posting it in a comment. extremely hard to read it that way and very spammy.

**Comment by Shark5588** [comment]
Hi, SerpentDrago. I just wonted to point out on Kodi 17.6 after fresh install of open wizard you don't get pop up of the settings , if I go in maintenance setting to auto clean on startup- clear cach on startup - clear packages on startup, Then restart kodi it doesn't auto clean.

But when I tested on Kodi 18.6 open wizard works ok on startup.
Sorry for any mistakes my first time.Thanks

https://pastebin.com/VCkKkBzU (kodi.log)
https://pastebin.com/N47U38SL (wizard log)

[wizard.log](https://github.com/drinfernoo/plugin.program.openwizard/files/4462125/wizard.log)

[kodi.log](https://github.com/drinfernoo/plugin.program.openwizard/files/4462119/kodi.log)

**Comment by drinfernoo** [comment]
This is something that had to be done in Kodi 17.x versions, in order to keep the script from running twice. With Kodi Krypton now being outmoded for a couple of years, I'd say it's simply time to move on. I'll actually be removing this "feature" entirely at some point, which ends up causing all sorts of weird things on Krypton.
