### ISSUE TITLE
[Bug] Failing Path Check

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#82]
I downloaded the openwizard zip file to my download folder.
Used install from zip in Kodi to install the openwizard zip.
Install went OK.
Now every time I run kodi I get the message in the attached file.
Is this normal and I just say OK on every kodi run, or is there something I need to fix?
I am using a Kodi 19 nightly, in portable mode, on my windows 10 laptop.
![Screenshot_9](https://user-images.githubusercontent.com/47518199/78968368-45d29f80-7afc-11ea-892b-23ccd03a647f.png)

**Comment by SerpentDrago** [comment]
this appears to me to be a bug with kodi 19.

is there any particular reason your running 19? it's not exactly ready for prime time.

**Comment by Jeffers24** [comment]
For prime time I am using Kodi 18, currently 18.6.

The reason I am using 19 early is that I got caught out when Kodi 18 was officialy released and updated my prime time system. The skin I was using wasn't compatible Aeon Nox 5 and I had issues with some addons not working.

Having been caught out once I have taken steps to keep my prime time system as Kodi 18.x, even when 19 is officially released.

So my use of 19 is just to get a working 19 build in parallel to using 18.x, such that I can replace my 18 build with, when 19 and addons are stable enough. I realise this will be many months from now.

Thank you for your efforts with the Open Wizard, making it work with Kodi 19.

On the basis this is a Kodi 19 issue I am happy to close this :-)

**Comment by SerpentDrago** [comment]
no need to close if it's a valid issue. me or Dr will just have tp replicate. the wizards goal is to be fully compatable with 19

please provide a link to full debug log and replicate issue thanks

**Comment by Jeffers24** [comment]
My log is here:- https://paste.kodi.tv/itowitecaq

**Comment by drinfernoo** [comment]
I can't quite see why it's happening, but I do think it's a bug.

**Comment by drinfernoo** [comment]
Your log file has expired, but 2.0.0 added Kodi 19 support. Please open this again with a new log if you're still having this issue.
