### ISSUE TITLE
Error in Log File[Bug]

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#83]
When testing the openwizard I noticed it was telling me I had 1 error in my log.
The error is in attached file.
Is this something I should be concerned/do something about?
![Screenshot (209)](https://user-images.githubusercontent.com/47518199/78968583-e628c400-7afc-11ea-8c65-a115f5840001.png)

**Comment by drinfernoo** [comment]
Doesn't look bad, but it's not my add-on 🤷🏼‍♀️

**Comment by Jeffers24** [comment]
Thanks for response, only noticed once I installed your wizard.
I will try and find out which addon it is and report to them.
