### ISSUE TITLE
[Bug] Could not Select Delete Packages on First Run Popup

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#84]
After installing openwizard from zip and doing first run, the popup appeared giving me the option to change settings.
I was not able to change the delete packages setting.
I was able to change the other settings in the popup.
To change the delete packages on startup I use the openwizard configuration option

**Comment by SerpentDrago** [comment]
auto cleanup on start is generally considered a bad idea. because people would use it to clear cache/artwork. which is unnecessary and causes general 
slowdowns and stresses meta data providers. 

the auto cleanup on startup can as you have seen still be done but is only configurable from settings now. this is to discourage its use by people that are not aware

**Comment by Jeffers24** [comment]
Thanks for response.
I have used cleanup on start for a number of years.
I found my folders for thumbnails, cache and packages just kept getting bigger.
Are you saying I don't need to do cleanup on startup?
If I don't do it on startup when would the folders be cleaned?

**Comment by SerpentDrago** [comment]
correct the thumbnails and cache and packages SHOULD be getting bigger . its saves having to wait for that info to be fetched from remote meta sites . speeds up menu load times . and generally stresses  the nice free meta sites we rely on less ! 

If every user of kodi fetched artwork / meta data every single time for every single item . the Free metadata sites we rely on for making kodi look nice will shut down !  not to mention its faster loading from cache then from remote !

only reason to cleanup would be if your running out of space after awhile or actually have a issue / artwork mismatch you want reset . :)

**Comment by Jeffers24** [comment]
I use the cleanup on startup as I set up a box for my non technical 70+ year old sister and she wouldn't be checking memory usage and running manual cleanups.
I still think the fact you can't set the delete packages on the first run popup is a bug?
The popup shows the option but you can't change it, whereas you can change the other options such as clear cache.

**Comment by Jeffers24** [comment]
No need to rush this as it can be set in openwizard configuration

**Comment by kodiultimate** [comment]
Just to add little bit. Kodi itself has been set up to clear packages folder when folder gets 200mb in size. So it will never go bigger than 200mb.

**Comment by drinfernoo** [comment]
I can't replicate this. @Jeffers24, what device are you using?

**Comment by Jeffers24** [comment]
@drinfernoo  I am using a laptop, windows 10 OS.
Seeing you could not recreate it I had another check on my laptop, after deleting the OpenWizard folder in userdata>addons.
The OpenWizard first run popup appears.
Using my mouse pad when I move the mouse over the options in the popup they become highlighted and I can change them with the exception of the last one displayed in the popup window, which is 'Clear Packages on Startup'.
Then, I used my up and down buttons and I could highlight and change 'Clear Packages on Startup'. Not only that but using my down arrow button I found 'Clear Packages on Startup' was not the last setting I could change, under it was the setting 'Clear Old Thumbnails on Startup'.
The issue appears to be that when using my mouse pad I cannot highlight and change the last option displayed in the initial popup window. However using my up and down directional keys I can.
Would it be possible to make the first run popup display all options without having to scroll?
Grasping at straws, this may also fix the issue with the mouse not highlighting what appears to be the last option in the popup?

**Comment by Jeffers24** [comment]
A bit of further testing.
After using my down key to display the last setting in the popup menu, when I moved my mouse over clear packages and clear old thumbs they ere highlighted and I could change them.
However, the setting 'Keep My Real Debrid' that was now at the top of the popup window I could not highlight with my mouse.
My non technical view is that if the size of th popup window was made larger so that all the optional settings were displayed this issue may go away?

**Comment by drinfernoo** [comment]
My approach would likely be to replace the custom window with an `xbmcgui.Dialog().multiselect(...)`.

**Comment by Jeffers24** [comment]
I am not technical to know what your response means, I assume it will be better and in some future release.
I can live with things as they are, so this is not urgent.

**Comment by tapwizard** [comment]
Just change the size of box and move "continue" button a little.
Firstrunsavedata.xml - in "grouplist" id="9000" change the height (520) to 560--on line 52
and move the "continue" button id"201" by changing to <top>685</top>from 675-- on line 304

**Comment by SerpentDrago** [comment]
> Just change the size of box and move "continue" button a little.
> Firstrunsavedata.xml - in "grouplist" id="9000" change the height (520) to 560--on line 52
> and move the "continue" button id"201" by changing to 685from 675-- on line 304

While this may "fix the issue" for most people . the problem with using xml is its so damn skin dependent/resolution dependent / etc  . Dr's tried to take the "make it universal " approach with the wizard . 

I'll check out your proposed changes to the xml . and see if that also fix's mouse issues . 


@Jeffers24 Trust me when i say its best to NOT use a mouse in kodi , it can cause all kinds of issues depending on the skin or addon xml in use . but i'll take a look

**Comment by tapwizard** [comment]
Absolutely agree, those changes were for Xonfluence skin. I just gave the areas that can be edited to stop the scrolling issue when using a mouse (OCD). Yes , mouse can be finicky depending on the skin.

**Comment by SerpentDrago** [comment]
Should be fixed in this PR .  #95 

Added scroll bar in case list gets bigger in future / expanded dialog / fixed alignment preventing last item being highlighted

**Comment by Jeffers24** [comment]
Excellent, thanks

**Comment by SerpentDrago** [comment]
the above should fix it , disregard the other PR  , #96 is correct ,  95 is not
