### ISSUE TITLE
Menu Background Transparency

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#85]
Would it be possible to make the menu background more transparent, so that the fanart can be seen more clearly?
Fanart is clear to the right of the menu background, and reduced behind the menu background. Hopefully screenshot will clarify my words.
![Screenshot (212)](https://user-images.githubusercontent.com/47518199/79062829-63873c80-7c95-11ea-85d4-2bae69305f40.png)

**Comment by SerpentDrago** [comment]
This has NOTHING to do with the addon . addons provide  icons / fanart / thumbnails / meta data to the kodi skin . its up to your skin how it actually displays those elements . 

so you will need to modify your skin , or check your skin settings in kodi for options to do what you want (if they provide them )

**Comment by drinfernoo** [comment]
Yeah, unfortunately this is a skin issue, where your skin (Aeon Nox SiLVO, maybe?) isn't showing very much of the background, via some design choices that are, in my opinion, questionable 😅

**Comment by Jeffers24** [comment]
Understand, the skin is Aeon Nox SiLVO, I'll ask the question in Kodi forum.
