### ISSUE TITLE
Editing uservar.py

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#87]
When editing the uservar.py file I could not find entries/default example, for the two fields below which are referenced in the OpenWizard wiki

CACHETEXT | Whether or not to "cache" the specified text files. Can be   either 'Yes' or 'No'.
-- | --
WIZARDFILE | A URL to a text file that contains the auto-updating information. This   is typically found within builds.txt, and can be left   as the default.

**Comment by drinfernoo** [comment]
Ah, it's actually because those two fields have been removed. Thanks for the heads up!

**Comment by Jeffers24** [comment]
Oh, I never saw or used the cachetext field before.

I do use the wizardfile url field as I don't have a repo and issue wizard updates from my hosted files on dropbox.

I am going to post an error log I got in a minute, when trying to auto update my wizard from using a wizardfile url pointing to my dropbox.

**Comment by drinfernoo** [comment]
Use `BUILDFILE` along with a file that matches the format shown on the wiki.

**Comment by Jeffers24** [comment]
I use a build file 'autobuilds.txt'
Are you saying when I set AUTOUPDATE = Yes as below paste, that I don't need to specify a url, as OpenWizard uses a url specified somewhere else?
#########################################################
#        Auto Update For Those With No Repo             #
#########################################################
# Enable Auto Update 'Yes' or 'No'
AUTOUPDATE = 'Yes'
