### ISSUE TITLE
Error on AutoUpdate Wizard from Dropbox

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#88]
I updated my wizard and made updates to my autobuild.txt file
The new wizard popup was displayed and I chose to update wizard
During/After install I got a wizard error, my log is here:- https://paste.kodi.tv/viwamejawo
Any pointers/ideas how I can fix this?

If you need a more detailed log, let me know what to switch on and I'll try to recreate.

**Comment by AxPhantom** [comment]
I received the very same issue just today aswell, never had it before.

**Comment by Jeffers24** [comment]
> I received the very same issue just today aswell, never had it before.

What OS and version of Kodi are you using?

I am using windows 10 and a Kodi 19 nightly

**Comment by drinfernoo** [comment]
Your log file has expired, but 2.0.0 added Kodi 19 support. Please open this again with a new log if you're still having this issue.
