### ISSUE TITLE
Where Is the Text 'OpenWizard' Used in The Menus Stored

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#90]
I have changed the name of the wizard, however OpeWizard is still being used in some drop down menus.
I have had a good look around the folders/files and can't find it.
Where is this text stored so that I can edit it?
![Screenshot_14](https://user-images.githubusercontent.com/47518199/79735867-dc6b4180-82f0-11ea-84ff-f4f919e6ee08.png)

**Comment by 45Record** [comment]
Uservar.py line 66

**Comment by Jeffers24** [comment]
Excellent, thanks for response.

**Comment by drinfernoo** [comment]
@Jeffers24 thanks @record_45 🙏
