### ISSUE TITLE
APK Installer Option Not Showing After Opening Wizard

### ISSUE THREAD

**Issue by Jeffers24** [a4k-openproject/plugin.program.openwizard#92]
I have checked my APK text file format, it matches the OpenWizard wiki file  format.
I have copied and pasted my APK text file url from Uservar into internet browser and the text file downloads correctly.
The APK text file I am using is the one from my Aftermath wizard that works OK.
Any pointers as to what I can check/change to get APK installer option to display?

**Comment by 45Record** [comment]
Give this a try and see if it works as I had issues with my builds.txt from my aftermath. 

Copy your text from your apk.txt from aftermath and paste it in the apk.txt file located in resources > text > apk.txt and use that in replace of your aftermath txt. 

Not sure if it’ll work, but it’s worth a try.

**Comment by Jeffers24** [comment]
> Give this a try and see if it works as I had issues with my builds.txt from my aftermath.
> 
> Copy your text from your apk.txt from aftermath and paste it in the apk.txt file located in resources > text > apk.txt and use that in replace of your aftermath txt.
> 
> Not sure if it’ll work, but it’s worth a try.

Looking at the APK text files from Aftermath and OpenWizard, in Aftermath the file is called apk.txt, in OpenWizard it is called apks.txt?

After copying the apk.txt file content from Aftermath to apks.txt in OpenWizard:-
   - How does OpenWizard know to look in it's apks.txt file for data?
   -  DO I need to remove my https url link for the APK text file in Uservar?

I noticed another entry missing from the wizard menu options, see pic below:-
![Screenshot_15](https://user-images.githubusercontent.com/47518199/79958910-5deedb00-847b-11ea-8178-a286d195fba7.png)

**Comment by 45Record** [comment]
If I understand what you’re saying you need to keep your apks.txt url at line #25. Just make sure like you mentioned to have it labeled apks.txt, not apk.txt

The other section you mentioned are just for icons. I doubt anything missing from there will effect your apks.txt to work correctly.

**Comment by Jeffers24** [comment]
Renamed my APK text file on Dropbox to apks.txt, did necessary changes to wizard, rezipped, was asked to install new wizard, installed, opened wizard and still no APKs option on wizard menu.

I snapshotted and arrowed the paths for ICONSPEED and ICONAPK to show that they were in the wizard and not left as 'http://', so shouldn't have been ignored.

I modded the dropbox link on line 25
![Screenshot_16](https://user-images.githubusercontent.com/47518199/79976386-6bfd2580-8494-11ea-9463-42083eebf493.png)

I want to keep my text files and icons outwith the wizard and access them via urls, so I can change as much as possible without having to edit, zip and issue a wizard update

**Comment by drinfernoo** [comment]
@Jeffers24, are you running Kodi 18.x?

**Comment by Jeffers24** [comment]
Gave up on trying to slowly do a Kodi 19 build. Installed the Kodi 19 21/04 nightly and it rejected the OpenWizard as not compatible :-( along with other things like Version Check. Seemed to be taking me backwards so I will leave 19 for a while.

Yes, I am using Kodi 18.6 on android from the playstore.

Apologies for not stating.

**Comment by drinfernoo** [comment]
The APK function does not work, and has thus been disabled, on version greater than 17.6. There are a handful of existing issues here outlining it, and it is unlikely to get fixed.

**Comment by Jeffers24** [comment]
How can I enable the APK function again?
Is it a check somewhere in the wizard and if Kodi version is greater than 17.6 don't display APK option.
I know it won't install on Kodi 18, but it will download and I can install the apk with my file explorer.
What about the second menu item ICONSPEED entry in my post above, which in aftermath displays as Internet Tools?

**Comment by drinfernoo** [comment]
@Jeffers24 There is a check for it, yes, so that it won't show in versions greater than 17.6.

There is a well-documented core Kodi permissions bug that prohibits install, so I won't be adding support until that is fixed.

**Comment by Jeffers24** [comment]
I wasn't going to ask you to make the change.

I would like to know where the check is so I can change it in my version of your wizard?

What about the second menu item ICONSPEED entry in my post above, which in aftermath displays as Internet Tools?

**Comment by drinfernoo** [comment]
The version check is here: https://github.com/drinfernoo/plugin.program.openwizard/blob/master/resources/libs/gui/main_menu.py#L72

And the "Network Tools" menu is now declared here: https://github.com/drinfernoo/plugin.program.openwizard/blob/master/resources/libs/gui/maintenance_menu.py#L194

It now uses the ICONMAINT icon for that particular menu, but ICONSPEED on the items inside.

**Comment by Jeffers24** [comment]
Many thanks for the url to the APK check.
I changed the <18 to >16 and it worked as in screen shot below.
![Screenshot_17](https://user-images.githubusercontent.com/47518199/80065230-b2ed2880-8531-11ea-89ca-30eb2d1e58a2.png)
I'll have a look at the 'Network Tools' next

**Comment by Jeffers24** [comment]
Thanks again for clarifying that 'Network Tools' is still there and can be accessed via:-
Maintenance >Misc Maintenance >Network Tools.
