### ISSUE TITLE
"Edit my whitelist" takes one minute to open[Bug]

### ISSUE THREAD

**Issue by cg00001** [a4k-openproject/plugin.program.openwizard#98]
Using Kodi v18.6 on Manjaro Linux.

On previous versions of the wizard it opened after a few seconds.

**Comment by drinfernoo** [comment]
Can you provide a log file or anything?

**Comment by cg00001** [comment]
> Can you provide a log file or anything?

This is from the build I'm using -Xenon Plus v3.3.
https://paste.ubuntu.com/p/4y6hxTYyqd

This is from an empty Kodi, with just Open Wizard installed.
https://paste.ubuntu.com/p/j35T4mbYh5

**Comment by drinfernoo** [comment]
According to your clean log file, this is you choosing the menu item to edit the whitelist:

```2023: 2020-05-30 21:17:41.295 T:139621308788544   DEBUG: RunScriptWithParams - calling plugin [COLOR limegreen]Open[/COLOR]Wizard('plugin://plugin.program.openwizard/','-1','?mode=whitelist&name=edit','resume:false')```

Followed by the select dialog showing up, 8.028s later:

```2236: 2020-05-30 21:17:49.323 T:139621308788544 DEBUG: ------ Window Init (DialogSelect.xml) ------```

After that, there are a number of window events from that dialog, and the the script stops, meaning you have finished your task, 12.816s after that.

```2283: 2020-05-30 21:18:02.139 T:139619924440832    INFO: Python interpreter stopped```

You entire interaction took 20.844s. 

This time will be directly proportional to the number of add-ons you have installed, so if it's taking too long, I'd suggest uninstalling any add-ons you don't use on a regular basis, and any dependencies that are orphaned in the process.

**Comment by cg00001** [comment]
> According to your clean log file, this is you choosing the menu item to edit the whitelist:
> 
> `2023: 2020-05-30 21:17:41.295 T:139621308788544 DEBUG: RunScriptWithParams - calling plugin [COLOR limegreen]Open[/COLOR]Wizard('plugin://plugin.program.openwizard/','-1','?mode=whitelist&name=edit','resume:false')`
> 
> Followed by the select dialog showing up, 8.028s later:
> 
> `2236: 2020-05-30 21:17:49.323 T:139621308788544 DEBUG: ------ Window Init (DialogSelect.xml) ------`
> 
> After that, there are a number of window events from that dialog, and the the script stops, meaning you have finished your task, 12.816s after that.
> 
> `2283: 2020-05-30 21:18:02.139 T:139619924440832 INFO: Python interpreter stopped`
> 
> You entire interaction took 20.844s.
> 
> This time will be directly proportional to the number of add-ons you have installed, so if it's taking too long, I'd suggest uninstalling any add-ons you don't use on a regular basis, and any dependencies that are orphaned in the process.

That doesn't explain why in previous versions of the wizard with the same amount (and maybe larger) of addons, it only took a few seconds to open the Whitelist dialog.
Thanks for your time.
