### ISSUE TITLE
[Bug] Quick Configure advanced settings

### ISSUE THREAD

**Issue by JayDee696969** [a4k-openproject/plugin.program.openwizard#99]
Im sure I missed a few updates to the wizard, but my question is what happened to the Quick configure advance settings GUI? Was that removed on purpose, or is this intended? All i see now is two settings for low ram and high ram devices. But I assume these are presets and are not actually reading the current free ram and setting it accordingly correct? It seems now you have to use one of the presets and then go back and adjust it? I think im just a bit confused how this section is setup now.

**Comment by SerpentDrago** [comment]
it was switched to a text based / normal menu on purpose . you can setup your own presets if wanted .  or set it to the exact value you want .  the old gui based one was a mess and not able to be improved upon . 

This is not a bug . 

https://github.com/drinfernoo/plugin.program.openwizard/wiki/Packaging-advancedsettings.xml-Files

**Comment by drinfernoo** [comment]
The custom window for it was removed because it was outdated, broken (from my memory), and I intended on redesigning the entire section... but I didn't get around to finishing it. Currently, you're correct. You can download a preset (even the default one), and then modify it after the fact.

For the record, you can do both of those things without a reboot I'm between, followed by a reboot, and it will work just fine.

**Comment by JayDee696969** [comment]
> it was switched to a text based / normal menu on purpose . you can setup your own presets if wanted . or set it to the exact value you want . the old gui based one was a mess and not able to be improved upon .
> 
> This is not a bug .
> 
> https://github.com/drinfernoo/plugin.program.openwizard/wiki/Packaging-advancedsettings.xml-Files

Ok, so it no longer is able to read your current device free ram and create the advanced settings accordingly right? Its only generic presets that arent specific to the device our using?

**Comment by JayDee696969** [comment]
Doesnt seem like an effective way to set advanced settings. Different devices, different amounts of free ram, different results that cant be determined by a preset value.

**Comment by SerpentDrago** [comment]
90 percent of devices fit into 3 category's  

low ram  (1 gig ) 
high ram  (2gigs or more ) 
0 cache (write to disk) (pc's or streaming box with hd for kodi ) 

Kodi should never really be set to more then 300 meg cache size anyways  else you have random weird issues . 

You could make about 4 presets and have 99.99 percent of devices covered .  

People that don't know enough to set it custom themselves (which you can do inside wizard ) should be fine with a preset . or not touching it at all .

**Comment by SerpentDrago** [comment]
also when you go quick configure advancedsettings > network and cache >  and click memory size it will auto detect what you should set it to as suggested

**Comment by JayDee696969** [comment]
> also when you go quick configure advancedsettings > network and cache > and click memory size it will auto detect what you should set it to as suggested

I understand and agree with your responses, but dont you agree that it would make more sense to autodetect the values first and then write the advanced settings? I mean, thats kinda the whole point of setting them, isnt it?

**Comment by drinfernoo** [comment]
No, it isn't the point. The point is that you *can* configure it. If you use this to adjust your settings, you can easily change it to the recommended value that it calculates for you.
